CREATE TABLE IF NOT EXISTS digest_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel TEXT NOT NULL DEFAULT 'stdout',
  status TEXT NOT NULL DEFAULT 'started',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
